### ISSUE TITLE
Not work for GitLab repository

### ISSUE THREAD

**Issue by hanyk** [upstash/context7#946]
Not work for GitLab repository such as https://gitlab.com/binary_c/binary_c/

**Comment by fahreddinozcan** [comment]
Hey @hanyk, I've manually triggered the parsing for this repo. There seems to be a problem in the input validator on our website. We'll send the fix for this.

**Comment by enesgules** [comment]
We have fixed this issue in our input validator, thanks for reporting!

**Comment by hanyk** [comment]
Thanks a lot! However, other GitLab repository, such as https://gitlab.lam.fr/cigale/cigale, still not work?

**Comment by enesgules** [comment]
We will support these types of libraries soon, please follow #885
